In [1]:
import torch
import numpy as np

In [40]:
m0 = torch.tensor(np.array([1.]))
m1 = torch.tensor(np.array([0.2, 0.8]))
mx = torch.tensor(np.ones([2, 3, 2]))
ms = torch.tensor(np.array([[0.3, 0.4, 0.3], [0.1, 0.8, 0.1]]))

In [21]:
m0 * m1

tensor([ 0.2000,  0.8000], dtype=torch.float64)

In [22]:
m1 * m1

tensor([ 0.0400,  0.6400], dtype=torch.float64)

In [23]:
torch.matmul(m1, m1)

tensor(0.6800, dtype=torch.float64)

In [41]:
mx.size()

torch.Size([2, 3, 2])

In [42]:
ms.size()

torch.Size([2, 3])

In [59]:
(ms.unsqueeze(2).expand_as(mx) * mx)[1,2,:]

tensor([ 0.1000,  0.1000], dtype=torch.float64)

In [65]:
mw = torch.tensor(np.array([-0.1, 0.3]))

In [66]:
torch.matmul(mx, mw)

tensor([[ 0.2000,  0.2000,  0.2000],
        [ 0.2000,  0.2000,  0.2000]], dtype=torch.float64)